#exclude: ["README.md"]
title: Billy Mitchell
description: Cognition & Neuroscience PhD Student
show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
aux_links:
  "Billy Mitchell's GitHub":
    - "//github.com/wj-mitchell"
aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
# logo: 
# google_analytics:
# ga_tracking:
# ga_tracking_anonymize_ip: true
