#exclude: ["README.md"]
title: Billy Mitchell
description: Cognition & Neuroscience PhD Student
show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
plugins:
- jekyll-remote-theme
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
# logo: 
# google_analytics:
# ga_tracking:
# ga_tracking_anonymize_ip: true
