project:
  type: website
  output-dir: docs

website:
  title: "William Mitchell"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: pages/projects.qmd
        text: Research Projects
      - href: pages/F99K00.qmd
        text: NIH F99/K00 Information
      - href: pages//Resume.pdf
        text: Resume
      - href: pages/CV.pdf
        text: CV

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: assetys/css/style.css
    toc: true
    

editor: source
