---
title: "About Me"
format: 
  html:
    page-layout: full
---

Hi, I'm Billy Mitchell

I'm a fifth-year PhD Candidate in Chelsea Helion's [Social and Affective Neuroscience lab](https://www.tu-sanlab.com/) who uses naturalistic paradigms to study neural representations of uncertainty, emotion, and self-regulation. I also co-direct the [Coding Outreach Group](https://tu-coding-outreach-group.github.io) which is a student-led organization aiming to increase computer programming literacy and to build an educational community with self-generated resources for coders of all levels.
  
I'd graduated from Loyola University Maryland, after which I coordinated some really interesting [nicotine](https://www-nejm-org.libproxy.temple.edu/doi/10.1056/NEJMsa1502403?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%3dwww.ncbi.nlm.nih.gov) and [cannabinoid studies](https://academic-oup-com.libproxy.temple.edu/jat/article/41/2/83/2967155) at [Johns Hopkins University](https://www.hopkinsmedicine.org/psychiatry/research/bpru) and [GI microbiome research](https://www-tandfonline-com.libproxy.temple.edu/doi/full/10.1080/19490976.2022.2083417?tab=permissions&scroll=top) at the [Children's Hospital of Philadelphia](https://www.chop.edu/centers-programs/division-gastroenterology-hepatology-and-nutrition). 

When I'm not working, I like hiking, playing Dungeons & Dragons (See my R functions in the [DnDRuf Repo](https://github.com/wj-mitchell/DnDRuf) or my [Combat Simulator App](https://wjpmitchell3.shinyapps.io/CombatSim/)!), and making [music](https://doorprizeband.bandcamp.com/releases). 
